### ISSUE TITLE
switch qsocks code to enigma  

### ISSUE THREAD

**Issue by QlikPreSalesDACH** [QlikPreSalesDACH/Qlik-Sense-Agent#2]
Due to the end of support for qsocks at the end of the year we need to switch the qsocks code to enigma.

**Comment by mpignon** [comment]
Hi, where are you with this switch to Enigma (end of support 2017-12-19) ?

```
## Deprecation Notice - 2016-12-19  
With the release of [enigma.js](https://github.com/qlik-oss/enigma.js) qsocks will be deprecated.  
Support for new QIX methods will be provided for 12 months (2017-12-19) and after that support will end. 
```

We still find this piece of code in sense-search.js:
```
      else if(connectionType=="Enigma"){
        **//we're connecting with a QSocks connection**
        this.connection = options.session;
        this.seqId = this.connection.rpc.requestId;
      }
```
Thank you.

**Comment by QlikPreSalesDACH** [comment]
Hi, I'm currently working on a version that only uses enigma. I will upload the new version of the Qlik Sense Agent as soon as the work is done.

**Comment by mpignon** [comment]
Ok, thank you. :)

**Comment by QlikPreSalesDACH** [comment]
Switched communication with Engine API from qsocks to enigmajs with version 1.1.0
