### ISSUE TITLE
Metadata app does not work with November release

### ISSUE THREAD

**Issue by lyonsdave** [QlikPreSalesDACH/Qlik-Sense-Agent#3]
It looks like the column structure of the Postgres db has changed thus breaking the metadata collection.

**Comment by mpignon** [comment]
@lyonsdave, it could be easy for you to adapt the Load Script in "QSA - Metadata App.qvf" to the November release's QSR structure, isn't it ?

**Comment by lyonsdave** [comment]
I just installed the Nov 2017 release.  The "Deleted" and "Sync Date" columns are no longer in the Apps table.  I was able to comment those out and get the Metadata to load, but that was just a temp fix.

**Comment by mpignon** [comment]
I installed QSA on Qlik Sense 3.1.SR1 and Qlik Sense 3.1.SR2 and it works.

The "Deleted" column for App is only used to filter out the "Deleted Apps".
![image](https://user-images.githubusercontent.com/26485143/32840589-664bb360-ca18-11e7-9a5b-dd40b8b17881.png)
So you could probably find another kind of "Status" column to filter out the "Deleted Apps", or just remove the `where "Deleted" = 'FALSE'` clause to load all apps in a first try.

The "Sync Date" column for App is never used in QSA.

Edit the Load Script "Apps" Section of "QSA - Metadata App.qvf" like this is working for me:
![image](https://user-images.githubusercontent.com/26485143/32840803-fbfdc06a-ca18-11e7-80a3-d92cf31561ed.png)
But of course giving 88 Apps in place of 70 "Non Deleted" Apps.

**Comment by QlikPreSalesDACH** [comment]
A new Meta Application has been added to the repository that solves the issue.
