### ISSUE TITLE
Would it be feasible to install QSA without GMS as a Mashup ?

### ISSUE THREAD

**Issue by mpignon** [QlikPreSalesDACH/Qlik-Sense-Agent#4]
Hello,
As QSA without GMS is using only 1 route (/qsa/ui), is it feasible to install QSA as a Mashup ?

What could be the limitations and risks ?
How would you proceed ?

The goal is to avoid to install one more NodeJS server next to the Qlik Sense server.

Thank you,
Mathieu @ PIT Business

**Comment by mpignon** [comment]
I tried and managed to deploy Qlik Sense Agent as a Mashup on Qlik Sense Enterprise 3.1 SR2.

If the **features are working** as it is with QSA on a dedicated NodeJS, the **weakness is about performances** at initial load.
- QSA with dedicated NodeJS, init page load is done after about 1,70s.
- QSA as a Mashup, init page load is done after about 40s.

On the Qlik Community, it seems to be a well known issue with Qlik Sense mashups.

I managed to go down to 17s by cleaning not needed dependencies, but it remains too long.

-----
For any help or expert advice about Qlik Sense, please visit www.pit-business.com

**Comment by QlikPreSalesDACH** [comment]
Hi mpignon, 

it is possible to run QSA as a mashup. I have attached a running version that doesn't need node.js but it is using qsocks for now.

[QSA_mashup.zip](https://github.com/QlikPreSalesDACH/Qlik-Sense-Agent/files/1611073/QSA_mashup.zip)

In case of any question feel free to let me know,

**Comment by mpignon** [comment]
Thanks a lot !
And what about the Init Load performances ?
Is it runing as well as with a dedicated Node.js (<1.70s) ?

--------------------
For any help or expert advice about Qlik Sense, please visit www.pit-business.com

**Comment by QlikPreSalesDACH** [comment]
Should be something around that. On my client it get's loaded instantly.

Just for information: I'm using the Qlik Sense Client Folder (C:\Program Files\Qlik\Sense\Client).

Just place the folder here and than try to access it via: https://hostname/resources/QSA_mashup/index.html

**Comment by mpignon** [comment]
That seems to be a good track.
- Actually, the mashup is installed on D:\ProgramData\Qlik\Sense\StaticContent\Extensions\QSA => **17 sec for initial load.**
- If if deploy the mashup in D:\Program Files\Qlik\Sense\Client\resources\QSA => https://myserver.com/resources/QSA/QSA.html **initial load in <2 sec.** :)

Thank you.
-----------
For any help or expert advice about Qlik Sense, please visit www.pit-business.com
