### ISSUE TITLE
App card shows 0 Dimension if only 1 Dimension exist for an App (Same for Measure)

### ISSUE THREAD

**Issue by mpignon** [QlikPreSalesDACH/Qlik-Sense-Agent#5]
If an application has only 1 Dimension, or only 1 Measure, the results show 0 Dimensions & 0 Measures:
![image](https://user-images.githubusercontent.com/26485143/34997311-738b5af4-fadc-11e7-8029-7485cf73683e.png)

But in "QSA - Metadata App.qvf", we can see that my app has 1 Measure & 1 Dimension:
![image](https://user-images.githubusercontent.com/26485143/34997553-16b596f4-fadd-11e7-9766-300efcc9e0e7.png)

**Comment by mpignon** [comment]
Indeed, in QSA.js, these expressions are false:
DIMCOUNT = `=if( substringcount(aggr(concat({<[Dimension]=>}[Dimension],','),[ID-App_ID]),',')>= 1, substringcount(aggr(concat({<[Dimension]=>}[Dimension],','),[ID-App_ID]),',')+1,0)`
MESCOUNT = `=if( substringcount(aggr(concat({<[Measure]=>}[Measure],','),[ID-App_ID]),',')>= 1, substringcount(aggr(concat({<[Measure]=>}[Measure],','),[ID-App_ID]),',')+1,0)`

![image](https://user-images.githubusercontent.com/26485143/34997608-364a04aa-fadd-11e7-8bc5-9e2105fa826e.png)

**And should be:**
DIMCOUNT = `=if( len(aggr(concat({<[Dimension]=>}[Dimension],','),[ID-App_ID]))>= 1, substringcount(aggr(concat({<[Dimension]=>}[Dimension],','),[ID-App_ID]),',')+1,0)`
MESCOUNT = `=if( len(aggr(concat({<[Measure]=>}[Measure]),[ID-App_ID]),',')>= 1, substringcount(aggr(concat({<[Measure]=>}[Measure],','),[ID-App_ID]),',')+1,0)`

**Or if you want to include the Drill Down Dimensions, simply:**
DIMCOUNT = `=aggr(COUNT({<[Dimension]=>}[Dimension]),[ID-App_ID])`
MESCOUNT = `=aggr(COUNT({<[Measure]=>}[Measure]),[ID-App_ID])`

![image](https://user-images.githubusercontent.com/26485143/34998824-6bdb8686-fae0-11e7-86de-e5358b9792db.png)

![image](https://user-images.githubusercontent.com/26485143/34998786-5440345e-fae0-11e7-9d93-bfde744180c1.png)

**Comment by QlikPreSalesDACH** [comment]
Fixed with version 1.1.0
